server:
  port: 8888

logging:
  path: logs
  file: CRM.log

spring:
  application:
    name: CRM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mooc?useSSL=false
    username: root
    password: a123456.

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*